version: "3.9"

services:
    web:
        build: .
        command: bash -c "python manage.py makemigrations app && python manage.py migrate app && python manage.py runserver 0.0.0.0:8000"
#            sh -c "python3 manage.py migrate &&
#            python /usr/src/app/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
    redis:
        image: redis:latest
    celery:
        restart: always
        build: .
        command: celery -A proj_alerts worker -l info -P eventlet
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
            - web
    celery-beat:
        build: .
        command: celery -A proj_alerts.celery beat -l info
        volumes:
            - .:/usr/src/app
        depends_on:
            - web
            - redis

