# Generated by Django 4.1.1 on 2022-09-08 17:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='[-+]?\\d{11}')], verbose_name='Номер телефона')),
                ('operator', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)], verbose_name='Код оператора')),
                ('tag', models.CharField(choices=[('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior')], default='JR', max_length=2)),
                ('timezone', models.CharField(choices=[('MSK', 'UTC+3'), ('AST', 'UTC−4'), ('CET', 'UTC+1')], default='MSK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.DateTimeField(blank=True, verbose_name='Начало отправки')),
                ('finish', models.DateTimeField(blank=True, verbose_name='Завершение отправки')),
                ('filter_tag', models.CharField(max_length=2)),
                ('filter_operator', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=datetime.datetime)),
                ('status_sending', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client')),
                ('sending', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sending')),
            ],
        ),
    ]
