# Generated by Django 4.1.1 on 2022-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='filter_operator',
        ),
        migrations.RemoveField(
            model_name='sending',
            name='filter_tag',
        ),
        migrations.AddField(
            model_name='sending',
            name='filter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='operator',
            field=models.PositiveIntegerField(verbose_name='Код оператора'),
        ),
    ]
