# Generated by Django 4.1.1 on 2022-09-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sending_filter_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sending',
            old_name='filter',
            new_name='filter_client',
        ),
    ]
