# Generated by Django 4.1.1 on 2022-09-13 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_filter_sending_filter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='app.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 19, 41, 21, 975663)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send', to='app.sending'),
        ),
    ]
