# Generated by Django 4.1.1 on 2022-09-14 18:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_client_alter_message_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 21, 7, 47, 968590)),
        ),
    ]
