# Generated by Django 4.1.1 on 2022-09-14 18:36

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_phonenumber_alter_message_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=12, unique=True, validators=[app.models.phone_number_is_valid], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 21, 36, 25, 636891)),
        ),
    ]
