# Generated by Django 4.1.1 on 2022-09-14 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_phonenumber_alter_message_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 21, 36, 28, 109914)),
        ),
    ]
