# Generated by Django 4.1.1 on 2022-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sending',
            name='filter_client',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sending',
            name='finish',
            field=models.DateTimeField(verbose_name='Завершение отправки'),
        ),
    ]
